
name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      terraformVersion:
        description: 'Terraform version'
        required: true
        default: '0.14.6'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform_configurations/mainbucket/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ github.events.inputs.terraformVersion }}
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, version.
    - name: Terraform init
      run: terraform init
    - name: Terraform plan
      run: terraform plan
